name: 'Tests'

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '5 5 * * 5'
    
jobs:
  unit-testing-iOS: 
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show xcodebuild version
      run: xcodebuild -version
    - name: Show xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: iOS
        scheme: 'PerseusDarkMode'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
  
  unit-testing-macOS: 
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show xcodebuild version
      run: xcodebuild -version
    - name: Show xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: macOS
        scheme: 'PerseusDarkMode'
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
        
